CREATE USER 
'videojuegos2526'@'localhost' 
IDENTIFIED BY 'Videojuegos2526$';

GRANT USAGE ON *.* TO 'videojuegos2526'@'localhost';

ALTER USER 'videojuegos2526'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON videojuegos2526.* 
TO 'videojuegos2526'@'localhost';

FLUSH PRIVILEGES;